### ISSUE TITLE
What is the biggest gauge wire that will fit into the + / - main power input? 

### ISSUE THREAD

**Issue by 121940kz** [bobko69/8PortLEDDistro#4]
If running all 8 outputs at like 5 amps that's roughly 40A wouldnt you need like 6 gauge wire for your main power input? Can you tell me what it would fit? Thanks!

**Comment by 121940kz** [comment]
And i guess to clarify, is the resettable fuse 4 amp hold / 8 amp trip is that TOTAL on the board or does that apply independently for each channel output? Thanks!

**Comment by bobko69** [comment]
i use 12awg wire in my set up.  the connector data sheet says it will hold up to 10awg.  the 4 amp hold / 8 amp trip is per fuse per port according to the data sheet of the fuse.

**Comment by 121940kz** [comment]
> i use 12awg wire in my set up. the connector data sheet says it will hold up to 10awg. the 4 amp hold / 8 amp trip is per fuse per port according to the data sheet of the fuse.

Thanks so if I used 7 outputs with an average of 5 or 6 amps each output, you don't see any issues with that. And use 10 ga input wire to be safe

**Comment by bobko69** [comment]
that should work fine.  a totally safe scenario would be 12v pixels, 12 power supply 300 pixels per port.  if you want to do 600 pixels per port you should do power injection between pixel 300 and 301 (or at the end at pixel 600) on each port.  this is about the maximum WLED can handle because the more pixels you add the lower the frame rate will drop.
